### ISSUE TITLE
Crashes siriproxy on plugin request

### ISSUE THREAD

**Issue by flash66** [hjaltij/SiriProxy-Plex#4]
Any ideas? IP is set correctly, siriproxy recognizes config.yml string for @host etc. 

[Info - Guzzoni] Received Object: SpeechRecognized
[Info - Plugin Manager] Processing 'Play Star Trek the original series season one episode seven '
[Info - Plugin Manager] Processing plugin #SiriProxy::Plugin::Plex:0x007f872c2284f8
[Info - Plugin Manager] Matches (?i-mx:(play|playing)(.+))
[Info - Plugin Manager] Applicable states: 
[Info - Plugin Manager] Current state: 
[Info - Plugin Manager] Matches, executing block
/Users/Stark/.rvm/rubies/ruby-1.9.3-p0/lib/ruby/1.9.1/open-uri.rb:346:in `open_http': 404 Not Found (OpenURI::HTTPError)
    from /Users/Stark/.rvm/rubies/ruby-1.9.3-p0/lib/ruby/1.9.1/open-uri.rb:775:in`buffer_open'
    from /Users/Stark/.rvm/rubies/ruby-1.9.3-p0/lib/ruby/1.9.1/open-uri.rb:203:in `block in open_loop'
    from /Users/Stark/.rvm/rubies/ruby-1.9.3-p0/lib/ruby/1.9.1/open-uri.rb:201:in`catch'
    from /Users/Stark/.rvm/rubies/ruby-1.9.3-p0/lib/ruby/1.9.1/open-uri.rb:201:in `open_loop'
    from /Users/Stark/.rvm/rubies/ruby-1.9.3-p0/lib/ruby/1.9.1/open-uri.rb:146:in`open_uri'
    from /Users/Stark/.rvm/rubies/ruby-1.9.3-p0/lib/ruby/1.9.1/open-uri.rb:677:in `open'
    from /Users/Stark/.rvm/rubies/ruby-1.9.3-p0/lib/ruby/1.9.1/open-uri.rb:33:in`open'
    from /Users/Stark/.rvm/gems/ruby-1.9.3-p0/bundler/gems/SiriProxy-Plex-54c1874b7845/lib/plex_library.rb:21:in `xml_doc_for_path'
    from /Users/Stark/.rvm/gems/ruby-1.9.3-p0/bundler/gems/SiriProxy-Plex-54c1874b7845/lib/plex_library.rb:26:in`all_shows'
    from /Users/Stark/.rvm/gems/ruby-1.9.3-p0/bundler/gems/SiriProxy-Plex-54c1874b7845/lib/plex_library.rb:106:in `find_show'
    from /Users/Stark/.rvm/gems/ruby-1.9.3-p0/bundler/gems/SiriProxy-Plex-54c1874b7845/lib/siriproxy-plex.rb:64:in`block in class:Plex'
    from /Users/Stark/.rvm/gems/ruby-1.9.3-p0/bundler/gems/cora-15d199d3af0b/lib/cora/plugin.rb:41:in `instance_exec'
    from /Users/Stark/.rvm/gems/ruby-1.9.3-p0/bundler/gems/cora-15d199d3af0b/lib/cora/plugin.rb:41:in`block (2 levels) in process'
zlib(finalizer): the stream was freed prematurely.
zlib(finalizer): the stream was freed prematurely.
flashs-iMac:siriproxy Stark$

**Comment by flash66** [comment]
When it defaults to looking at local music I get this return which shows the config data. This doesn't crash. 

Create server for iPhone connection
start conn #<SiriProxy::Connection::Iphone:0x007fdc31852c20 @signature=5, @processed_headers=false, @output_buffer="", @input_buffer="", @unzipped_input="", @unzipped_output="", @unzip_stream=#<Zlib::Inflate:0x007fdc318522e8>, @zip_stream=#Zlib::Deflate:0x007fdc31852220, @consumed_ace=false, @name="iPhone", @ssled=false>
[Info - Plugin Manager] Plugins laoded: [#<SiriProxy::Plugin::Plex:0x007fdc31856e10 @host="192.168.0.150", @port="32400", @tv_index="2", @plex_library=#<PlexLibrary:0x007fdc31856be0 @host="192.168.0.150", @port="32400", @tv_index="2">, @manager=#<SiriProxy::PluginManager:0x007fdc31850f10 @plugins=[...]>>, #<SiriProxy::Plugin::Example:0x007fdc3185c518 @manager=#<SiriProxy::PluginManager:0x007fdc31850f10 @plugins=[...]>>]
Create server for iPhone connection

**Comment by hjaltij** [comment]
Not sure, you could try to log out the url that it's trying to call.

Open up plex_library.rb and find this:

  def xml_doc_for_path(path)
    uri = "#{base_path}#{path}"
    xml_data = open(uri).read
    doc = REXML::Document.new(xml_data)
  end

above xml_data ... put this line

puts uri

And then see what uri it's trying to call when it crashes

**Comment by flash66** [comment]
Thanks H. I'll try it now. i read a couple of other people are having the same issue.

**Comment by flash66** [comment]
Doesn't report the URL in the crash. The .rb file is:

def xml_doc_for_path(path)
    uri = "#{base_path}#{path}"
    puts uri <-----
    xml_data = open(uri).read
    doc = REXML::Document.new(xml_data)

  end

[Info - Plugin Manager] Matches, executing block
/Users/Stark/.rvm/rubies/ruby-1.9.3-p0/lib/ruby/1.9.1/open-uri.rb:346:in `open_http': 404 Not Found (OpenURI::HTTPError)
    from /Users/Stark/.rvm/rubies/ruby-1.9.3-p0/lib/ruby/1.9.1/open-uri.rb:775:in`buffer_open'

**Comment by hjaltij** [comment]
That's strange, the previous stack trace looked like the crash was in this method.

**Comment by flash66** [comment]
Very strange! I literally have tried everything I could think of. Here is the latest stack with the 'puts uri'. I don't understand the URL call?? I tried this on 2 machines running Lion. Same error.  The first (old) plugin worked fine.  Hmmm

[Info - Plugin Manager] Processing 'Play the latest episode of that 70s show '
[Info - Plugin Manager] Processing plugin #SiriProxy::Plugin::Plex:0x007ff002acfb58
[Info - Plugin Manager] Matches (?i-mx:(play|playing) (the)? latest(.+) of(.+))
[Info - Plugin Manager] Applicable states: 
[Info - Plugin Manager] Current state: 
[Info - Plugin Manager] Matches, executing block
/Users/Stark/.rvm/rubies/ruby-1.9.3-p0/lib/ruby/1.9.1/open-uri.rb:346:in `open_http': 404 Not Found (OpenURI::HTTPError)
    from /Users/Stark/.rvm/rubies/ruby-1.9.3-p0/lib/ruby/1.9.1/open-uri.rb:775:in`buffer_open'
    from /Users/Stark/.rvm/rubies/ruby-1.9.3-p0/lib/ruby/1.9.1/open-uri.rb:203:in `block in open_loop'
    from /Users/Stark/.rvm/rubies/ruby-1.9.3-p0/lib/ruby/1.9.1/open-uri.rb:201:in`catch'
    from /Users/Stark/.rvm/rubies/ruby-1.9.3-p0/lib/ruby/1.9.1/open-uri.rb:201:in `open_loop'
    from /Users/Stark/.rvm/rubies/ruby-1.9.3-p0/lib/ruby/1.9.1/open-uri.rb:146:in`open_uri'
    from /Users/Stark/.rvm/rubies/ruby-1.9.3-p0/lib/ruby/1.9.1/open-uri.rb:677:in `open'
    from /Users/Stark/.rvm/rubies/ruby-1.9.3-p0/lib/ruby/1.9.1/open-uri.rb:33:in`open'
    from /Users/Stark/.rvm/gems/ruby-1.9.3-p0/bundler/gems/SiriProxy-Plex-54c1874b7845/lib/plex_library.rb:21:in `xml_doc_for_path'
    from /Users/Stark/.rvm/gems/ruby-1.9.3-p0/bundler/gems/SiriProxy-Plex-54c1874b7845/lib/plex_library.rb:26:in`all_shows'
    from /Users/Stark/.rvm/gems/ruby-1.9.3-p0/bundler/gems/SiriProxy-Plex-54c1874b7845/lib/plex_library.rb:106:in `find_show'
    from /Users/Stark/.rvm/gems/ruby-1.9.3-p0/bundler/gems/SiriProxy-Plex-54c1874b7845/lib/siriproxy-plex.rb:188:in`play_latest_episode_of'
    from /Users/Stark/.rvm/gems/ruby-1.9.3-p0/bundler/gems/SiriProxy-Plex-54c1874b7845/lib/siriproxy-plex.rb:57:in `block in <class:Plex>'
    from /Users/Stark/.rvm/gems/ruby-1.9.3-p0/bundler/gems/cora-15d199d3af0b/lib/cora/plugin.rb:41:in`instance_exec'
    from /Users/Stark/.rvm/gems/ruby-1.9.3-p0/bundler/gems/cora-15d199d3af0b/lib/cora/plugin.rb:41:in `block (2 levels) in process'
zlib(finalizer): the stream was freed prematurely.

**Comment by flash66** [comment]
Problem is corrected. The HTTP call was looking for the proper TV index. I made sure all of my TV shows were in a library called "TV" and my config.yml had the proper index # which mine was "18" instead of the default "2"

**Comment by hjaltij** [comment]
Cool =)
